-- PostgreSQL Compatible Schema for Events and Cafes
-- Run this AFTER db_schema_postgres.sql

-- Events table
CREATE TABLE IF NOT EXISTS events (
    event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(200) NOT NULL,
    event_description TEXT,
    event_picture VARCHAR(500),
    ticket_price DECIMAL(15, 2) NOT NULL CHECK (ticket_price >= 0),
    ticket_template TEXT,
    event_date TIMESTAMP,
    event_location VARCHAR(200),
    airtel_money_code VARCHAR(100),
    airtel_money_id VARCHAR(100),
    airtel_qr_image VARCHAR(500),
    max_tickets INT DEFAULT NULL,
    tickets_sold INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(user_id) ON DELETE SET NULL
);

-- Event Tickets table
CREATE TABLE IF NOT EXISTS event_tickets (
    ticket_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    user_id INT NOT NULL,
    ticket_code VARCHAR(50) UNIQUE NOT NULL,
    purchase_amount DECIMAL(15, 2) NOT NULL,
    ticket_status VARCHAR(20) DEFAULT 'valid' CHECK (ticket_status IN ('valid', 'used', 'cancelled')),
    qr_code_data TEXT,
    purchased_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP NULL,
    FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Event Ticket Inventory table
CREATE TABLE IF NOT EXISTS event_ticket_inventory (
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    serial_number VARCHAR(100) NOT NULL,
    is_assigned BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMP NULL,
    ticket_id INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (event_id, serial_number),
    UNIQUE (ticket_id),
    FOREIGN KEY (event_id) REFERENCES events(event_id) ON DELETE CASCADE,
    FOREIGN KEY (ticket_id) REFERENCES event_tickets(ticket_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_event_assignment ON event_ticket_inventory (event_id, is_assigned);

-- Campus Cafes table
CREATE TABLE IF NOT EXISTS campus_cafes (
    cafe_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafe_name VARCHAR(200) NOT NULL,
    cafe_description TEXT,
    cafe_logo VARCHAR(500),
    airtel_money_code VARCHAR(50) NOT NULL,
    qr_code_image VARCHAR(500),
    is_active BOOLEAN DEFAULT TRUE,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(user_id) ON DELETE SET NULL
);

-- Campus Cafe Transactions table
CREATE TABLE IF NOT EXISTS cafe_transactions (
    cafe_txn_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cafe_id INT NOT NULL,
    user_id INT NOT NULL,
    amount DECIMAL(15, 2) NOT NULL CHECK (amount > 0),
    reference_code VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255),
    payment_method VARCHAR(20) DEFAULT 'airtel_money' CHECK (payment_method IN ('airtel_money', 'qr_code')),
    status VARCHAR(20) DEFAULT 'completed' CHECK (status IN ('pending', 'completed', 'failed')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cafe_id) REFERENCES campus_cafes(cafe_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_event_active ON events(is_active);
CREATE INDEX IF NOT EXISTS idx_ticket_code ON event_tickets(ticket_code);
CREATE INDEX IF NOT EXISTS idx_cafe_active ON campus_cafes(is_active);
CREATE INDEX IF NOT EXISTS idx_cafe_txn_ref ON cafe_transactions(reference_code);
