-- PostgreSQL Compatible Schema for Supabase
-- Run this in the Supabase SQL Editor

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(15) UNIQUE NOT NULL,
    email VARCHAR(255) NULL,
    registration_number VARCHAR(50) NULL,
    full_name VARCHAR(100) NOT NULL,
    university VARCHAR(100) NULL,
    pin_hash VARCHAR(255) NOT NULL,
    user_type VARCHAR(20) NOT NULL DEFAULT 'Student' CHECK (user_type IN ('Student', 'Merchant', 'Admin', 'StudentUnion', 'Person')),
    wallet_balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00 CHECK (wallet_balance >= 0),
    verification_code VARCHAR(6) NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    verification_expires_at TIMESTAMP NULL,
    avatar_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User Roles Table
CREATE TABLE IF NOT EXISTS user_roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('Person', 'Student', 'Merchant', 'Admin', 'StudentUnion')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Merchants Table
CREATE TABLE IF NOT EXISTS merchants (
    merchant_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    business_name VARCHAR(100) NOT NULL,
    qr_code_token VARCHAR(50) UNIQUE NOT NULL,
    agent_code VARCHAR(50) NULL,
    is_approved BOOLEAN DEFAULT FALSE,
    fee_paid BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Transactions Table
CREATE TABLE IF NOT EXISTS transactions (
    txn_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    txn_type VARCHAR(20) NOT NULL CHECK (txn_type IN ('QR_PAY', 'P2P', 'TOP_UP', 'SU_FEE', 'WITHDRAWAL', 'SYSTEM_FEE')),
    sender_id INT NOT NULL,
    receiver_id INT NOT NULL,
    amount DECIMAL(15, 2) NOT NULL CHECK (amount > 0),
    reference_code VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sender_id) REFERENCES users(user_id),
    FOREIGN KEY (receiver_id) REFERENCES users(user_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_phone ON users(phone_number);
CREATE INDEX IF NOT EXISTS idx_qr_token ON merchants(qr_code_token);
CREATE INDEX IF NOT EXISTS idx_txn_ref ON transactions(reference_code);

-- Student Union Table
CREATE TABLE IF NOT EXISTS student_union (
    su_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_type VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    reference_number VARCHAR(50) UNIQUE NOT NULL,
    student_name VARCHAR(100) NOT NULL,
    student_id VARCHAR(50) NOT NULL,
    program VARCHAR(100) NOT NULL,
    year INT NOT NULL,
    university VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    amount_paid DECIMAL(15, 2) NOT NULL CHECK (amount_paid >= 0),
    service_fee DECIMAL(15, 2) NOT NULL DEFAULT 0.00 CHECK (service_fee >= 0),
    total_amount DECIMAL(15, 2) NOT NULL CHECK (total_amount >= 0),
    recipient VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
